apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cqx1lb3tc-go-gitops
  description: This is GitOps manifest for cqx1lb3tc-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=cqx1lb3tc-go
    backstage.io/kubernetes-id: cqx1lb3tc-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: cqx1lb3tc-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:cqx1lb3tc-go
