apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cqx1lb3tc-go
  janus-idp.io/tekton: cqx1lb3tc-go
  backstage.io/kubernetes-id: cqx1lb3tc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cqx1lb3tc-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
